name: Tests
on: [push, pull_request]

jobs:
  tests:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy-3.7]
        include:
        - python-version: 3.6
          env:
            TOXENV: py
        - python-version: 3.7
          env:
            TOXENV: py
        - python-version: 3.8
          env:
            TOXENV: py
        - python-version: 3.9
          env:
            TOXENV: py
        - python-version: pypy-3.7
          env:
            TOXENV: pypy

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libxml2 and libxslt development packages on Ubuntu
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 'pypy-3.7'
      run: sudo apt install libxml2-dev libxslt-dev
    # https://www.lfd.uci.edu/~gohlke/pythonlibs/
    - name: Install libxml2 and libxslt development packages on Windows
      if: matrix.os == 'windows-latest' && matrix.python-version == 'pypy-3.7'
      run: pip install https://download.lfd.uci.edu/pythonlibs/y2rycu7g/lxml-4.6.3-pp37-pypy37_pp73-win_amd64.whl

    - name: Run tests
      env: ${{ matrix.env }}
      run: |
        pip install -U tox
        tox

    - name: Upload coverage report
      if: matrix.os == 'ubuntu-latest'
      run: bash <(curl -s https://codecov.io/bash)
